# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:
      AMO_ISSUER: ${{ secrets.AMO_ISSUER }}
      AMO_SECRET: ${{ secrets.AMO_SECRET }}
      AMO_ID: ${{ secrets.AMO_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set BUILD_ID for unique sign version
      run: echo '::set-env name=BUILD_ID::'${{ github.run_id }}$(( ( RANDOM % 10 ) ))
    - run: npm run version
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
